$content = Get-Content 'leaders-talk.html' -Raw -Encoding UTF8

$replacements = @{
    "Trang ch?u" = "Trang chủ"
    "Kh?i Vn Phng" = "Khối Văn Phòng"
    "Kh?i Th? Tr? ng" = "Khối Thị Trường"
    "Kh?i Hng N?ng" = "Khối Hàng Nặng"
    "Tm ki?m kha h?c..." = "Tìm kiếm khóa học..."
    "S? KI?N HOT NH?T 2026" = "SỰ KIỆN HOT NHẤT 2026"
    "H?c ? hnh" = "Học để hành"
    "Khng ph?i ? dnh" = "Không phải để dành"
    "Leaders Talk khng dnh cho ng? i ch? mu?n ng?i nghe cho h?t gi?. y l ni nh?ng Business Leader th?t b?c ln sn khu ? bc tch cc v?n ? au u nh?t trong cng vi?c: ?i ng? khng ch?y, KPI khng ?t, v?n hnh r?i, quy?t ?nh sai v p l?c ch?ng p l?c. Khng slide mu m, khng l thuy?t sch v?, ch? c cu chuy?n th?t, gc nhn th?t v nh?ng cu?c tranh lu?n th?ng ?n t?n g?c v?n ?. B?n ?n khng ph?i ? `"h?c thm m?t ki?n th?c`", m ? mang v? t duy, gi?i php v cu tr? l?i th?c chi?n cho chnh bi ton mnh ang m?c k?t." = "Leaders Talk không dành cho người chỉ muốn ngồi nghe cho hết giờ. Đây là nơi những Business Leader thật bước lên sân khấu để bóc tách các vấn đề đau đầu nhất trong công việc: đội ngũ không chạy, KPI không đạt, vận hành rối, quyết định sai và áp lực chồng áp lực. Không slide màu mè, không lý thuyết sách vở, chỉ có câu chuyện thật, góc nhìn thật và những cuộc tranh luận thẳng đến tận gốc vấn đề. Bạn đến không phải để `"học thêm một kiến thức`", mà để mang về tư duy, giải pháp và câu trả lời thực chiến cho chính bài toán mình đang mắc kẹt."
    "ng k ngay" = "Đăng ký ngay"
    "Di?n gi?a" = "Diễn giả"
    "H?c vin/Workshop" = "Học viên/Workshop"
    "B?n s? nh?n ? c g?" = "Bạn sẽ nhận được gì?"
    "M?i workshop ?u ? c thi?t k? ? mang l?i gi tr? th?c t? nh?t cho cng vi?c hng ngy c?a b?n." = "Mỗi workshop đều được thiết kế để mang lại giá trị thực tế nhất cho công việc hàng ngày của bạn."
    "Gc nhn th?c chi?n" = "Góc nhìn thực chiến"
    "Khng ph?i l thuy?t. B?n ? c nghe cch ng? i th?t ang x? l v?n ? th?t  th? b?n c th? em v? p d?ng ngay ngy mai." = "Không phải lý thuyết. Bạn được nghe cách người thật đang xử lý vấn đề thật – thứ bạn có thể đem về áp dụng ngay ngày mai."
    "o su pain point" = "Đào sâu pain point"
    "Nh?ng v?n ? `"au nhng t ai ni`" s? ? c mang ln bn: ?i ng?, KPI, v?n hnh, p l?c v m? x? ?n t?n g?c." = "Những vấn đề `"đau nhưng ít ai nói`" sẽ được mang lên bàn: đội ngũ, KPI, vận hành, áp lực… và mổ xẻ đến tận gốc."
    "Tranh lu?n tr?c di?n" = "Tranh luận trực diện"
    "Khng ch? nghe  b?n ? c h?i th?ng, ph?n bi?n, challenge di?n gi?a ? tm ra gc nhn ph h?p nh?t v?i mnh." = "Không chỉ nghe – bạn được hỏi thẳng, phản biện, challenge diễn giả để tìm ra góc nhìn phù hợp nhất với mình."
    "Gi?i php th?c t?" = "Giải pháp thực tế"
    "R?i bu?i khng ch? c insight, m c lun cch lm c? th? ? x? l bi ton b?n ang m?c k?t." = "Rời buổi không chỉ có insight, mà có luôn cách làm cụ thể để xử lý bài toán bạn đang mắc kẹt."
    "T?ng quan" = "Tổng quan"
    "Di?n gi?a" = "Diễn giả"
    "S?p Di?n Ra" = "Sắp Diễn Ra"
    "Cn t ch?" = "Còn ít chỗ"
    "VI?T PROMPT NG CCH V?I CNG TH?C CAO" = "VIẾT PROMPT ĐÚNG CÁCH VỚI CÔNG THỨC CAO"
    "inh H? Nho Thng" = "Đinh Hồ Nho Thông"
    "L ng Dng Nhn" = "Lương Dũng Nhân"
    "Hong Giang, ? inh Th ng, Ph?m T? Th?" = "Hoàng Giang, Đỗ Đình Thương, Phạm Từ Thứ"
    "Nguy?n Lm Hong Yn" = "Nguyễn Lâm Hoàng Yên"
    "Thm Tr?n, Ph?m Hong Long, Tr?n Th? Trung" = "Thơm Trần, Phạm Hoàng Long, Trần Thế Trung"
    "Gip ?c Th?ng" = "Giáp Đức Thắng"
    "Nguy?n Minh Trung" = "Nguyễn Minh Trung"
    "Kim L Huy" = "Kim Lê Huy"
    "Nguy?n Hong Nam" = "Nguyễn Hoàng Nam"
    "Ngn Tr?n" = "Ngân Trần"
    "Cao Tu?n Minh" = "Cao Tuấn Minh"
    "LNH ?O TRONG DNG CH?Y BI?N ?NG" = "LÃNH ĐẠO TRONG DÒNG CHẢY BIẾN ĐỘNG"
    "HI?U QU? B?T NG? CNG N8N" = "HIỆU QUẢ BẤT NGỜ CÙNG N8N"
    "I GI?A RANH GI?I - GI? V?N NGH?A TNH" = "ĐI GIỮA RANH GIỚI - GIỮ VẸN NGHĨA TÌNH"
    "GI? ? C TM - M?I V N ? C T?M" = "GIỮ ĐƯỢC TÂM - MỚI VƯƠN ĐƯỢC TẦM"
    "G?P S?P HUY: H?I I - ?NG C SUY" = "GẶP SẾP HUY: HỎI ĐI - ĐỪNG CÓ SUY"
    "LEVEL UP! - B?T PH HI?U SU?T C NHN & ?I NG? CNG PH NG PHP 3UP" = "LEVEL UP! - BỨT PHÁ HIỆU SUẤT CÁ NHÂN & ĐỘI NGŨ CÙNG PHƯƠNG PHÁP 3UP"
    "THNG MINH C?M XC TRONG GIAO TI?P - BI?N TIU C?C THNH TCH C?C" = "THÔNG MINH CẢM XÚC TRONG GIAO TIẾP - BIẾN TIÊU CỰC THÀNH TÍCH CỰC"
    "TON DN AI: KHNG XI AI - AI XI MNH" = "TOÀN DÂN AI: KHÔNG XÀI AI - AI XÀI MÌNH"
    "CHO V NH?N PH?N H?I HI?U QU?" = "CHO VÀ NHẬN PHẢN HỒI HIỆU QUẢ"
    "D?N L?I T NG LAI - B?T PH THNH CNG" = "DẪN LỐI TƯƠNG LAI - BỨT PHÁ THÀNH CÔNG"
    "Xem l?i" = "Xem lại"
    "Gim ?c o t?o c?a H? th?ng Gio d?c ATY" = "Giám đốc Đào tạo của Hệ thống Giáo dục ATY"
    "Gi?i thi?t" = "Giới thiệu"
    "Gi?i thi?u" = "Giới thiệu"
    "Nghin c?u sinh Ti?n s? Generative AI t?i Edgewood University (Hoa K?)." = "Nghiên cứu sinh Tiến sĩ Generative AI tại Edgewood University (Hoa Kỳ)."
    "Th?c s? Lnh ?o Gio d?c  University of Queensland (c)." = "Thạc sĩ Lãnh đạo Giáo dục – University of Queensland (Úc)."
    "S? h?u ch?ng ch? PCC t? Lin on Khai v?n Qu?c t? ICF." = "Sở hữu chứng chỉ PCC từ Liên đoàn Khai vấn Quốc tế ICF."
    "?ng sng l?p H? th?ng Gio d?c ATY, CEO WISEDUCATION v nh sng l?p AIMastermind  n v? tin phong o t?o AI l?y con ng? i lm trung tm t?i Vi?t Nam." = "Đồng sáng lập Hệ thống Giáo dục ATY, CEO WISEDUCATION và nhà sáng lập AIMastermind – đơn vị tiên phong đào tạo AI lấy con người làm trung tâm tại Việt Nam."
    "C kinh nghi?m ?ng hnh v h?p tc cng AIA, VietinBank, Dai-ichi Life, VTV News, VUS, Home Credit..." = "Có kinh nghiệm đồng hành và hợp tác cùng AIA, VietinBank, Dai-ichi Life, VTV News, VUS, Home Credit..."
    "?ng th?i ?u ph?i v pht tri?n chuyn mn cho hng trm chuyn gia ?c l?p." = "Đồng thời điều phối và phát triển chuyên môn cho hàng trăm chuyên gia độc lập."
    "S? ? c c?p nh?t sau..." = "Sẽ được cập nhật sau..."
    "C?u Ph T?ng Gim ?c Kh?i Nhn l?c t?i T?p on Xy d?ng Ho Bnh" = "Cựu Phó Tổng Giám Đốc Khối Nhân lực tại Tập đoàn Xây dựng Hòa Bình"
    "C?u Ph T?ng Gim ?c Kh?i Nhn l?c t?i T?p on Xy d?ng Ho Bnh  m?t trong nh?ng t?p on xy d?ng hng u Vi?t Nam." = "Cựu Phó Tổng Giám Đốc Khối Nhân lực tại Tập đoàn Xây dựng Hòa Bình – một trong những tập đoàn xây dựng hàng đầu Việt Nam."
    "Hn 20 nm kinh nghi?m trong lnh v?c qu?n tr? nhn s?, pht tri?n t? ch?c v xy d?ng vn ha doanh nghi?m." = "Hơn 20 năm kinh nghiệm trong lĩnh vực quản trị nhân sự, phát triển tổ chức và xây dựng văn hóa doanh nghiệp."
    "Hn 20 nm kinh nghi?m trong lnh v?c qu?n tr? nhn s?, pht tri?n t? ch?c v xy d?ng vn ha doanh nghi?p." = "Hơn 20 năm kinh nghiệm trong lĩnh vực quản trị nhân sự, phát triển tổ chức và xây dựng văn hóa doanh nghiệp."
    "Chuyn gia t v?n chi?n l c nhn s? cho nhi?u doanh nghi?p l?n trong v ngoi n c." = "Chuyên gia tư vấn chiến lược nhân sự cho nhiều doanh nghiệp lớn trong và ngoài nước."
    "Phng H?c t?p v Pht tri?n" = "Phòng Học tập và Phát triển"
    "Tr? s?: Rivera Park, 7/28 Thnh Thi, Ph ng Din H?ng, TP. HCM" = "Trụ sở: Rivera Park, 7/28 Thành Thái, Phường Diên Hồng, TP. HCM"
    "Nguy?n Ng?c Mai Trm" = "Nguyễn Ngọc Mai Trâm"
    "CNG NGH? D?N D?T - HI?U SU?T `"BAY`" CAO" = "CÔNG NGHỆ DẪN DẮT - HIỆU SUẤT `"BAY`" CAO"
    "MY V?N HNH, NG I KI?N T?O: NNG T?M CNG NGH?, LM CH? AI" = "MÁY VẬN HÀNH, NGƯỜI KIẾN TẠO: NÂNG TẦM CÔNG NGHỆ, LÀM CHỦ AI"
    "T?ng quan" = "Tổng quan"
    "Di?n gi?" = "Diễn giả"
}

foreach ($key in $replacements.Keys) {
    $content = $content.Replace($key, $replacements[$key])
}

# Just in case there are missing question marks from the replacement, we'll try a regex for some common words.
$content = $content -replace "Trang ch\?u", "Trang chủ"
$content = $content -replace "Kh\?i V.n Ph.ng", "Khối Văn Phòng"
$content = $content -replace "Kh\?i Th\? Tr\?\?ng", "Khối Thị Trường"
$content = $content -replace "Kh\?i H.ng N\?ng", "Khối Hàng Nặng"
$content = $content -replace "T.m ki\?m kh.a h\?c...", "Tìm kiếm khóa học..."
$content = $content -replace "Di\?n gi\?a?", "Diễn giả"
$content = $content -replace "S\?p Di\?n Ra", "Sắp Diễn Ra"
$content = $content -replace "C.n .t ch\?", "Còn ít chỗ"
$content = $content -replace "\?inh H\? Nho Th.ng", "Đinh Hồ Nho Thông"

Set-Content 'leaders-talk.html' $content -Encoding UTF8
Set-Content 'workshop.html' $content -Encoding UTF8
Set-Content 'dien-gia.html' $content -Encoding UTF8
Write-Host "Fixed file contents."
